<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="mower">
  <!-- ============================================================ -->
  <!-- Vineyard Mower Robot URDF                                     -->
  <!-- All dimensions sourced from existing codebase:                -->
  <!--   - Wheel separation: embedded/arduino/src/motor_control.h   -->
  <!--   - LiDAR position: mower_bringup/launch/lidar.launch.py     -->
  <!-- ============================================================ -->

  <!-- Properties from existing codebase - DO NOT CHANGE -->
  <xacro:property name="wheel_separation" value="0.30"/>  <!-- motor_control.h:22 -->
  <xacro:property name="wheel_diameter" value="0.10"/>    <!-- motor_control.h:25 -->
  
  <!-- Chassis dimensions (estimated based on tracked robot form factor) -->
  <xacro:property name="chassis_length" value="0.40"/>
  <xacro:property name="chassis_width" value="0.35"/>
  <xacro:property name="chassis_height" value="0.15"/>
  
  <!-- LiDAR position from lidar.launch.py:62 - DO NOT CHANGE -->
  <xacro:property name="laser_x" value="0.07"/>
  <xacro:property name="laser_y" value="0.0"/>
  <xacro:property name="laser_z" value="0.17"/>

  <!-- IMU position (placeholder - center of chassis, slightly elevated) -->
  <xacro:property name="imu_x" value="0.0"/>
  <xacro:property name="imu_y" value="0.0"/>
  <xacro:property name="imu_z" value="0.05"/>

  <!-- Material definitions -->
  <material name="dark_grey">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>
  <material name="light_grey">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <!-- ============================================================ -->
  <!-- Base Link - Center of robot footprint                         -->
  <!-- ============================================================ -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <!-- ============================================================ -->
  <!-- Base Footprint - Ground plane reference for Nav2              -->
  <!-- ============================================================ -->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- Laser Frame - LiDAR sensor position                          -->
  <!-- Position from lidar.launch.py static TF publisher             -->
  <!-- ============================================================ -->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
    </collision>
  </link>
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- IMU Link - IMU sensor position (placeholder)                  -->
  <!-- Will be updated when IMU is physically integrated             -->
  <!-- ============================================================ -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>

  <!-- ============================================================ -->
  <!-- Track Links (visual representation of tracked drive)          -->
  <!-- ============================================================ -->
  <!-- Left Track -->
  <link name="left_track">
    <visual>
      <geometry>
        <box size="${chassis_length * 0.9} ${wheel_diameter} ${wheel_diameter}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>
  <joint name="left_track_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_track"/>
    <origin xyz="0 ${wheel_separation/2} ${wheel_diameter/2}" rpy="0 0 0"/>
  </joint>

  <!-- Right Track -->
  <link name="right_track">
    <visual>
      <geometry>
        <box size="${chassis_length * 0.9} ${wheel_diameter} ${wheel_diameter}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>
  </link>
  <joint name="right_track_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_track"/>
    <origin xyz="0 -${wheel_separation/2} ${wheel_diameter/2}" rpy="0 0 0"/>
  </joint>

</robot>
